# Generated by Django 5.1.4 on 2024-12-25 06:47

import django.contrib.auth.models
import django.db.models.manager
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='user',
            managers=[
                ('extra', django.db.models.manager.Manager()),
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.AddField(
            model_name='user',
            name='last_email_sent',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Последняя рассылка'),
        ),
    ]
