# Generated by Django 5.1.4 on 2024-12-24 04:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Weather',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time_epoch', models.PositiveBigIntegerField(verbose_name='Время UNIX')),
                ('time', models.DateTimeField(verbose_name='Время')),
                ('temp_c', models.FloatField(verbose_name='Температура C')),
                ('is_day', models.PositiveSmallIntegerField(verbose_name='Светлое время суток')),
                ('condition', models.JSONField(verbose_name='Условия')),
                ('wind_kph', models.FloatField(verbose_name='Ветер, км/ч')),
                ('wind_degree', models.PositiveSmallIntegerField(verbose_name='Направление ветра, °')),
                ('wind_dir', models.CharField(max_length=16, verbose_name='Направление ветра')),
                ('pressure_in', models.FloatField(verbose_name='Давление, дюймы')),
                ('precip_mm', models.PositiveSmallIntegerField(verbose_name='Осадки, мм')),
                ('humidity', models.PositiveSmallIntegerField(verbose_name='Влажность, %')),
            ],
        ),
        migrations.AddField(
            model_name='city',
            name='timezone',
            field=models.CharField(blank=True, max_length=64, null=True, verbose_name='Таймзона'),
        ),
        migrations.CreateModel(
            name='Current',
            fields=[
                ('city', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='current', serialize=False, to='home.city')),
                ('weather', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='home.weather')),
            ],
        ),
        migrations.CreateModel(
            name='WeatherDay',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_epoch', models.PositiveBigIntegerField(verbose_name='Время UNIX')),
                ('date', models.DateField(verbose_name='День')),
                ('maxtemp_c', models.FloatField(verbose_name='Max температура, °C')),
                ('mintemp_c', models.FloatField(verbose_name='Min температура, °C')),
                ('avgtemp_c', models.FloatField(verbose_name='Средняя температура, °C')),
                ('maxwind_kph', models.FloatField(verbose_name='Max скорость вектра, км/ч')),
                ('totalprecip_mm', models.FloatField(verbose_name='Осадки в течение дня, мм')),
                ('avghumidity', models.PositiveSmallIntegerField(verbose_name='Средняя влажность, %')),
                ('condition', models.JSONField(verbose_name='Условия')),
                ('city', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='weather', to='home.city')),
            ],
        ),
        migrations.AddField(
            model_name='weather',
            name='weather_day',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='hours', to='home.weatherday'),
        ),
    ]
