# Generated by Django 5.1.4 on 2024-12-24 05:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_weather_city_timezone_current_weatherday_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='current',
            name='weather',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='home.weather'),
        ),
    ]
