# Generated by Django 5.1.4 on 2024-12-24 20:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_alter_current_weather'),
    ]

    operations = [
        migrations.AddField(
            model_name='current',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
